### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by noraj** [ecrax/emoji-toolbox#1]
Hi can you push your extension to https://open-vsx.org/ in addition to VSCode Market Place so people using the FLOSS version could install it too?

I wrote [an article](https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/) on the subject.

**Comment by ecrax** [comment]
Hey, sorry for the late response. :)
But sure I can do that, I didn't even know that something like an alternative market place exists. Thank you for pointing me at this.

I will leave this repo open as a reminder for myself. :)

**Comment by ecrax** [comment]
The extension is now published [(here)](https://open-vsx.org/extension/ecrax/emoji-toolbox) :)
